fixes for zsh installation
hazelcast/hazelcast-commandline-client pull request #21
Opened 2021-09-28 13:53 UTC by utku-caglayan

2021-10-01 03:47 UTC, yuce requested changes
Looks good, except few changes.

Also, it would be better if variables are quoted, since they may include spaces.

2021-10-01 03:47 UTC, yuce commented on README.md
> +For bash:
How about: `### Bash`

2021-10-01 03:47 UTC, yuce commented on README.md
> +For zsh:
How about: `### Zsh`

2021-10-01 03:47 UTC, yuce commented on scripts/install.sh
> +echo "Installation for BASH:"
Let's use: `Bash`

2021-10-01 03:47 UTC, yuce commented on scripts/install.sh
> +mkdir -p $bash_completion_dir/completions
It's better to quote the arguments to guard against spaces in the variables. Also I would recommend writing the variable names in braces:
```
mkdir -p "${bash_completion_dir}/completions"
```

2021-10-01 03:47 UTC, yuce commented on scripts/install.sh
> +mkdir -p $HZCLI_HOME/autocompletion/bash
It's better to quote the arguments to guard against spaces in the variables. Also I would recommend writing the variable names in braces.

2021-10-01 03:47 UTC, yuce commented on scripts/install.sh
> +curl --silent "https://raw.githubusercontent.com/hazelcast/hazelcast-commandline-client/main/extras/bash_completion.sh" --output $HZCLI_HOME/autocompletion/bash/hz-cli
The same comment about quotes and braces here for `--output`.

2021-10-01 03:47 UTC, yuce commented on scripts/install.sh
> +ln -s $HZCLI_HOME/autocompletion/bash/hz-cli $bash_completion_dir/completions/hz-cli
The same comment about quotes and braces here.

2021-10-06 05:32 UTC, utku-caglayan commented on README.md
> +For bash:
Sure

2021-10-06 05:32 UTC, utku-caglayan commented on README.md
> +For zsh:
Sure

2021-10-06 05:34 UTC, utku-caglayan commented on scripts/install.sh
> +echo "Installation for BASH:"
Done, also to the Zsh log

2021-10-06 06:05 UTC, yuce approved these changes
Thanks, looks good!

2021-10-06 06:10 UTC, merged