Add atomic-long command [CLC-191]
hazelcast/hazelcast-commandline-client pull request #280
Opened 2023-06-06 07:45 UTC by mtyazici

2023-06-08 13:54 UTC, kutluhanmetin submitted a review, later dismissed
LGTM

2023-06-16 04:48 UTC, kutluhanmetin submitted a review, later dismissed

2023-06-20 04:30 UTC, yuce requested changes
Some minor ideas...

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long.go
> +	}
We can safely remove this. AtomicLong can't use a schema.

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long.go
> +		atomicLongName := ec.Props().GetString(atomicLongFlagName)
```suggestion
		name := ec.Props().GetString(atomicLongFlagName)
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_decrement_get.go
> +}
Do you think we can refactor the code for `AtomicLongDecrementGetCommand.Exec` and `AtomicLongIncrementGetCommand.Exec` to use the same function? They almost do the same thing.

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_decrement_get.go
> +			Name:  output.NameValue,
Let's use `Value` instead of `this`.

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_get.go
> +	cc.SetCommandUsage("get [flags]")
```suggestion
	cc.SetCommandUsage("get")
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_get.go
> +		sp.SetText(fmt.Sprintf("Setting value into atomicLong %s", ali.Name()))
```suggestion
		sp.SetText(fmt.Sprintf("Setting value into AtomicLong %s", ali.Name()))
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_decrement_get.go
> +		sp.SetText(fmt.Sprintf("Decrementing the atomic long %s", ali.Name()))
```suggestion
		sp.SetText(fmt.Sprintf("Decrementing the AtomicLong %s", ali.Name()))
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_get.go
> +			Name:  output.NameValue,
Let's use `Value` instead of `this`.

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_increment_get.go
> +			Name:  output.NameValue,
Let's use `Value` instead of `this`.

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_increment_get.go
> +		sp.SetText(fmt.Sprintf("Incrementing the atomic long %s", ali.Name()))
```suggestion
		sp.SetText(fmt.Sprintf("Incrementing the AtomicLong %s", ali.Name()))
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_set.go
> +	help := "Set the value of the atomic long"
```suggestion
	help := "Set the value of the AtomicLong"
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_decrement_get.go
> +	help := "Decrement the atomic long by the given value"
```suggestion
	help := "Decrement the AtomicLong by the given value"
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_get.go
> +	help := "Get the value of the atomic long"
```suggestion
	help := "Get the value of the AtomicLong"
```

2023-06-20 04:30 UTC, yuce commented on base/commands/atomic_long/atomic_long_set.go
> +		sp.SetText(fmt.Sprintf("Setting value of atomic long %s", ali.Name()))
```suggestion
		sp.SetText(fmt.Sprintf("Setting value of AtomicLong %s", ali.Name()))
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +atomic-long commands are a group of atomic long operations.
```suggestion
atomic-long commands are a group of AtomicLong operations.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +Get the value of the atomic long.
```suggestion
Get the value of the AtomicLong.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +Sets the value of the atomic long.
```suggestion
Sets the value of the AtomicLong.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +Increment the atomic long by the given value.
```suggestion
Increment the AtomicLong by the given value.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +|Name of the atomic-long.
```suggestion
|Name of the AtomicLong.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +Decrement the atomic long by the given value.
```suggestion
Decrement the AtomicLong by the given value.
```

2023-06-20 04:30 UTC, yuce commented on docs/modules/ROOT/pages/clc-atomic-long.adoc
> +|Name of the atomic-long.
```suggestion
|Name of the AtomicLong.
```

2023-06-21 07:17 UTC, merged