Add missing map commands [CLC-200]
hazelcast/hazelcast-commandline-client pull request #284
Opened 2023-06-08 13:18 UTC by mtyazici

Added following commands:
- map lock
- map try-lock
- map unlock
- map values

2023-06-09 07:49 UTC, kutluhanmetin commented on base/commands/map/map_lock.go
> +}
```suggestion
```

2023-06-09 08:21 UTC, kutluhanmetin submitted a review, later dismissed
Just a minor suggestion

2023-06-16 04:49 UTC, kutluhanmetin submitted a review, later dismissed

2023-07-05 13:58 UTC, yuce requested changes
Just trivial ideas...

2023-07-05 13:58 UTC, yuce commented on docs/modules/ROOT/pages/clc-map.adoc
> +clc map lock -n myMap --key-type string key1
```suggestion
clc map lock -n my-map --key-type string key1
```

2023-07-05 13:58 UTC, yuce commented on docs/modules/ROOT/pages/clc-map.adoc
> +clc map try-lock -n myMap --key-type string key1
```suggestion
clc map try-lock -n my-map --key-type string key1
```

2023-07-06 06:41 UTC, yuce approved these changes
Looks good!

2023-07-06 07:40 UTC, merged