Add demo generate-data command [CLC-206]
hazelcast/hazelcast-commandline-client pull request #289
Opened 2023-06-19 09:28 UTC by mtyazici

2023-08-10 08:13 UTC, yuce requested changes
Some ideas...

2023-08-10 08:13 UTC, yuce commented on internal/sse/event.go
> +			tmp.Data = append(tmp.Data, []byte("\n")...)
```suggestion
			tmp.Data = append(tmp.Data, '\n')
```

2023-08-10 14:52 UTC, yuce submitted a review, later dismissed
Looks good!

2023-08-11 08:55 UTC, mtyazici commented on base/commands/demo/demo_generate_data.go
> +		return ch, nil
I removed the ExecuteBlocking statement

2023-08-11 09:24 UTC, yuce approved these changes
Looks good!

2023-08-11 09:36 UTC, merged